name: Publish
on: [ push ]
concurrency: ci-${{ github.ref }}
jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI-SKIP]')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1.0.2
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref_name }}
      - name: Publish
        uses: uTen2c/publish-to-github@v1.1
        with:
          repo: ${{ secrets.REPO }}
          token-user: ${{ secrets.TOKEN_USER }}
          token: ${{ secrets.TOKEN }}
          publish-task: publish -Peula=true